### ISSUE TITLE
Running other files should not include extension

### ISSUE THREAD

**Issue by JonnyOThan** [maneatingape/rsvp#5]
I tried to deploy this library on a vessel that was already low on space.  There wasn't enough room.  I tried compiling the code to ksm files, which would fit - except the cross-file runpaths use the file extension.

If you don't use a file extension, the library can be used in either compiled or non-compiled form:

https://ksp-kos.github.io/KOS/commands/runprogram.html#automatic-guessing-of-full-filename

**Comment by maneatingape** [comment]
This is a good idea, will add to the next release.

As a quality of life improvement, we could even go a little further and add something like a `rsvp:compile_to` method, that would compile all the relevant source files then copy them to an destination of your choice, for example `rsvp:compile_to("1:/rsvp")`. This should save users the effort of manually compiling each file.

**Comment by maneatingape** [comment]
Fixed in commit 190fd55f2da0f6bea46d73e02ab62d2f9d4d138c
